spring:
  application:
    name: pls-calculate-parking-fee-service
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true