spring:
  application:
    name: pls-vehicle-service
  jpa:
    showSql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

server:
  port: 8089