spring:
  application:
    name: pls-vehicle-service
  jpa:
    showSql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://pls-discovery-service:8761/eureka
    fetchRegistry: true
    registerWithEureka: true