spring:
  application:
    name: discovery-service
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false